// src/components/playlist-selector.tsx
import { createResource, createSignal, For, type Component } from "solid-js";
import { createSpotify } from "../signals/createSpotify";

export const PlaylistSelector: Component<{
  setPlaylistId: (p: string) => void;
}> = (props) => {
  const spotify = createSpotify("http://localhost:5173/player");

  const [playlists] = createResource(spotify, async (sdk) => {
    if (!sdk) return null;
    return await sdk.currentUser.playlists.playlists();
  });

  const [selectedId, setSelectedId] = createSignal("");

  return (
    <div>
      {playlists.loading && <span>Loading...</span>}
      {playlists.error && <span>Error: {playlists.error.message}</span>}
      {playlists() && playlists().items && Array.isArray(playlists().items) && (
        <div class="bg-jjj-gradient flex justify-center items-center min-h-screen">
          <div class="flex flex-col gap-4 w-full max-w-4xl mx-auto px-4">
            <select
              id="playlist-select"
              value={selectedId()}
              onChange={(e) => setSelectedId(e.currentTarget.value)}
              class="w-full rounded-md bg-gray-400 text-white py-3 px-4 text-lg"
            >
              <option value="" disabled selected>
                Please select a playlist to shuffle...
              </option>
              <For each={playlists()?.items}>
                {(pl) => <option value={pl.id}>{pl.name}</option>}
              </For>
            </select>
            <button
              onClick={() => props.setPlaylistId(selectedId())}
              disabled={!selectedId()}
              class="w-full rounded-md  py-3 px-4 text-lg"
              classList={{
                "bg-gray-400 text-white" : selectedId() !== undefined,
                "bg-gray-300 text-gray-100 cursor-not-allowed opacity-60" : selectedId() === "",
              }}
            >
              Start the countdown
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// src/lib/components/PlaylistSelector.svelte
<script>
    export let playlists;
    export let startCountDown;
    let selectedPlaylist;
    let loading = false;
    async function handleClick() {
        loading = true;
        startCountDown(selectedPlaylist);
    }
</script>

<div class="wrapper">
    <div class="content-wrapper">
        {#if !loading}
            <select bind:value={selectedPlaylist}>
                <option selected disabled value={undefined}
                    >Please select a playlist to shuffle...</option
                >
                {#each playlists as playlist (playlist)}
                    <option value={playlist.id}>{playlist.name}</option>
                {/each}
            </select>
            <button
                disabled={selectedPlaylist === undefined}
                on:click|once={handleClick}>Start the countdown</button
            >
        {:else}
            <h2>loading the playlist...</h2>
        {/if}
    </div>
</div>

<style>
    h2{
        color:black;
    }
    .wrapper {
        text-align: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background: var(--gradient-0); /* Dark background color */
    }
    .content-wrapper {
        width: 45%;
    }
    select {
        border:none;
        font-size: 16px;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 10px;
        width: 100%; /* Make the dropdown 100% width */
        background-color: var(--gray-8);

        color: white;
    }
    select:focus {
        outline: none;
    }

    button {
        font-size: 18px;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #007bff; /* Blue button background color */
        color: white; /* White text color for the button */
        cursor: pointer;
        width: 100%; /* Make the button 100% width */
    }

    button:disabled {
        background-color: var(--gray-8); /* Gray out disabled button */
        cursor: not-allowed;
    }
</style>
